name: starter_template
version: 1.0.0

environment:
  sdk: ^2.17.0

dependencies:
  dart_appwrite:
  freezed_annotation: 
  json_annotation: 
  equatable:


dev_dependencies:
  lints: 
  build_runner: 
  freezed: 
  json_serializable: 
