name: starter_template
version: 1.0.0

environment:
  sdk: ^2.17.0

dependencies:
  dart_appwrite: 8.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable:


dev_dependencies:
  lints: ^2.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
